plugins {
    id 'signal-sample-app'
}

android {
    namespace 'org.signal.contactstest'

    defaultConfig {
        applicationId "org.signal.contactstest"
    }

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = '1.5.10'
    }
}

dependencies {
    implementation project(':contacts')
}